### ISSUE TITLE
Katie Conner Tasks

### ISSUE THREAD

**Issue by kconner3815** [kconner3815/TicketFinder.IO#5]
## Tasks: 
- [x] Research the Ticket Master API 
- [x] Make a pull request to get all files 
- [x] Set up HTML doc with form and buttons 
- [x] Look into new libraries
- [x] Write CSS / Create Responsive Design using bootstrap / foundation
