### ISSUE TITLE
Roland's Tasks

### ISSUE THREAD

**Issue by rolandtellez** [kconner3815/TicketFinder.IO#6]
## Tasks:
- [x] Research Ticketmaster API
- [ ] Pull project files
- [ ] Parse ajax response data
- [ ] Display event data on index.html (img, title, date, details)
