### ISSUE TITLE
Kellin Tasks

### ISSUE THREAD

**Issue by kconner3815** [kconner3815/TicketFinder.IO#7]
## Tasks 
- [x] Create firebase 
- [x] Add all team members as owners/ give permission so we have access
- [x] Determine what data we want to store in firebase 
- [x] Create firebase.JS file and push to project
